lib/swanye_web/router.ex
defmodule SwanyeWeb.Router do
  use SwanyeWeb,        :router;
  use KabareWeb.Router;

  pipeline(:browser) do
    plug(:accepts, ["html"]);
    plug(:fetch_session);
    plug(:fetch_live_flash);
    plug(:fetch_flash);
    plug(:protect_from_forgery);
    plug(:put_secure_browser_headers);
  end

  pipeline(:auth_layout) do
    plug(:put_layout, {SwanyeWeb.LayoutView, :auth});
  end

  pipeline(:users_layout) do
    plug(:accepts, ["html", "json", "jsonld", "activity+json"]);
    plug(:fetch_session);
    plug(:fetch_flash);
    plug(:protect_from_forgery);
    plug(:put_secure_browser_headers);
    plug(:put_layout, {SwanyeWeb.LayoutView, :users});
  end
  pipeline(:users_layout_without_protect) do
    plug(:accepts, ["html", "json", "jsonld", "activity+json"]);
    plug(:fetch_session);
    plug(:fetch_flash);
    plug(:put_secure_browser_headers);
    plug(:put_layout, {SwanyeWeb.LayoutView, :users});
  end

  pipeline(:search_layout) do
    plug(:put_layout, {SwanyeWeb.LayoutView, :search});
  end

  pipeline(:account_layout) do
    plug(:put_layout, {SwanyeWeb.LayoutView, :account});
  end

  pipeline(:dashboard_layout) do
    plug(:put_layout, {SwanyeWeb.LayoutView, :dashboard});
  end

  pipeline(:frontend_handling) do
    plug(:accepts, ["json", "jsonld", "activity+json"]);
    plug(:fetch_session);
    plug(:protect_from_forgery);
    plug(:put_secure_browser_headers);
  end

  pipeline(:api) do
    plug(:accepts, ["json", "jsonld", "activity+json"]);
  end

  scope "/", SwanyeWeb do
    pipe_through(:browser);

    get("/", PageController, :index);
  end

  scope "/", SwanyeWeb do
    pipe_through([:browser, :auth_layout]);

     get("/auth/sign_up",      AuthController, :new);
    post("/auth/sign_up",      AuthController, :create);

     get("/auth/confirmation", AuthController, :confirmation);

     get("/auth/sign_in",      AuthController, :sign_in);
    post("/auth/sign_in",      AuthController, :authorize);

     get("/auth/sign_out",     AuthController, :sign_out);
  end

  scope "/", SwanyeWeb do
    pipe_through([:users_layout]);

    get("/users/:actor",                  UsersController, :profile);
    get("/@:actor",                       UsersController, :profile);

    get("/users/:actor/followers",        UsersController, :followers);
    get("/@:actor/followers",             UsersController, :followers);

    get("/users/:actor/following",        UsersController, :following);
    get("/@:actor/following",             UsersController, :following);

    get("/users/:actor/statuses/:postID", UsersController, :post);
    get("/@:actor/:postID",               UsersController, :post);
  end
  scope "/", SwanyeWeb do
    pipe_through([:users_layout_without_protect]);

    post("/users/:username/inbox",             UsersController, :inbox);
    post("/inbox",                             UsersController, :shared_inbox);
  end

  scope "/", SwanyeWeb do
    pipe_through([:browser, :search_layout]);

    get("/search", SearchController, :search);
  end

  scope "/", SwanyeWeb do
    pipe_through([:browser, :account_layout]);

     get("/settings/account",       AccountController, :settings);
    post("/settings/account",       AccountController, :save);

     get("/settings/notifications", AccountController, :notifications);
  end

  scope "/", SwanyeWeb do
    pipe_through([:frontend_handling]);

    post("/frontend/search_by_partial_name", FrontendHandlingController, :search_by_partial_name);
    post("/frontend/like",                   FrontendHandlingController, :like);
    post("/frontend/reblog",                 FrontendHandlingController, :reblog);
    post("/frontend/delete",                 FrontendHandlingController, :delete);
    post("/frontend/follow",                 FrontendHandlingController, :follow);
    post("/frontend/post",                   FrontendHandlingController, :post);
  end

  scope "/", SwanyeWeb do
    pipe_through([:browser, :dashboard_layout]);

    
  end

  # Other scopes may use custom stacks.
  # scope "/api", SwanyeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SwanyeWeb.Telemetry
    end
  end
end

lib/swanye_web/views/layout_view.ex
defmodule SwanyeWeb.LayoutView do
  use SwanyeWeb, :view
end

lib/swanye_web/templates/layout/site_parts/carousel.html.eex
<SECTION id="<%= @prefix <> "_carousel" %>" class="carousel"
         aria-label="carousel"              tabindex="0">
  <A class="carousel__close"
     href="#close-modal"
     onclick="document.getElementById('<%= @prefix <> "_carousel" %>')
                      .style
                      .display = 'none'">
    &times;
  </A>

  <DIV class="slides">
    <%= for({image, index} <- @images |> Enum.with_index) do %>
          <% count = index + 1 %>

          <DIV id="slide-<%= "#{@prefix}_#{count}" %>"
               class="slides-item noselect"
               tabindex="0"
               aria-label="slide <%= count %> of <%= length(@images) %>">
            <IMG src="<%= Kabare.URLs.URL.to_string(image.object.url) %>"
                 alt="<%= image.object.name %>"
                 title="<%= image.object.name %>"                         />
          </DIV>
    <%  end %>
  </DIV>

  <DIV class="carousel__nav">
    <%= for({_image, index} <- @images |> Enum.with_index) do %>
          <% count = index + 1 %>

          <A class="slider-nav"
             href="#slide-<%= "#{@prefix}_#{count}" %>"
             aria-label="Go to slide <%= count %>">
            <%= count %>
          </A>
    <%  end %>
  </DIV>
</SECTION>

lib/swanye_web/templates/layout/site_parts/inner-post_template.html.eex
<%= if(@post.object_type !== "Tombstone") do %>
<% creator         = Enum.at(@post.actor_attributees, 0); %>
<% icons           = Enum.filter(creator.object.images || [], &(&1.is_icon)); %>
<% images          = Enum.filter(creator.object.images || [], &(!&1.is_icon)); %>
<% privacyLevel    = cond do
                       Enum.any?(@post.addressing_to_collections,
                                 &(Kabare.Utils
                                         .DatabaseUtils
                                         .to_ap_id(&1.addressee) === "https://www.w3.org/ns/activitystreams#Public" &&
                                   &1.addressing_type            === "to")) -> :public;
                       Enum.any?(@post.addressing_to_collections,
                                 &(Kabare.Utils
                                         .DatabaseUtils
                                         .to_ap_id(&1.addressee) === "https://www.w3.org/ns/activitystreams#Public" &&
                                   &1.addressing_type            === "cc")) -> :unlisted;
                       true                                                 -> :targeted;
                     end %>

<%= Enum.map(@post.replied_to_posts,
             &(render("site_parts/inner-post_template.html", user: @user,
                                                             post: &1,
                                                             init: @init))) %>

<HEADER class="dash_post-info<%= if length(@post.replied_to_posts) > 0, do: " top-border", else: " first-in-thread" %>">
  <%= if(length(@post.replied_to_posts) < 1) do %>
        <A href="<%= Kabare.URLs.URL.to_string(@init.activity_pub_id) %>"
           role="button"
           target="_blank"
           aria-label="Permalink"
           title="View post"
           class="orig-post-anchor">
          <DIV class="orig-post-button">
          </DIV>
        </A>
  <%  end %>

  <A href="<%= Kabare.Utils.ActivityPubUtils.profile_page_path(creator) %>">
    <IMG class="icon" src="<%= if(length(icons) > 0) do
                                 Kabare.URLs.URL.to_string(Enum.at(icons, 0).object.url);
                               else
                                 "/images/missing.png";
                               end %>">
  </A>

  <DIV class="post-info">
    <A class="poster ellipsize"
       href="<%= Kabare.Utils.ActivityPubUtils.profile_page_path(creator) %>">
      <%= if(creator.object.name) do %>
            <B class="ellipsize"><%= creator.object.name %></B>&nbsp;
      <%  end %>

      <SPAN class="ellipsize"><%= Kabare.Utils
                                        .ActivityPubUtils
                                        .activity_pub_handle(creator) %>&#10;&#10;</SPAN>
    </A>

    <DIV class="timestamp ellipsize">
      <I class="ellipsize">
        <%= case privacyLevel do
              :public   -> render("site_parts/buttons/public-post.html",   altText: "Public");
              :unlisted -> render("site_parts/buttons/unlisted-post.html", altText: "Unlisted");
              :targeted -> render("site_parts/buttons/targeted-post.html", altText: "Targeted");
            end %>

        <%= if(@post.published) do %>
          <%  pub = if(@user) do
                      Timex.Timezone.convert(@post.published, @user.timezone);
                    else
                      @post.published;
                    end; %>
          <%= Calendar.strftime(pub, "%a: %B %d, %Y ") %>&ndash; <A href="<%= Kabare.Utils.ActivityPubUtils.post_page_path(@post) %>"><%= Calendar.strftime(pub, "%I:%M:%S %p") %></A>
        <%  end %>
      </I>
    </DIV>
  </DIV>
</HEADER>

<ARTICLE class="dash_post-content"
         data-users="<%= Kabare.Utils.ActivityPubUtils.activity_pub_handle(creator) %>">
  <%= if(@post.summary) do %>
        <% cwCheckboxID = "content-warning-checkbox_"                   <>
                          Integer.to_string(@post.ap_id)                <>
                          Kabare.Utils.KabareUtils.generate_unique_id(); %>
        <INPUT type="checkbox"
               id="<%= cwCheckboxID %>"
               class="cwci">

        <SPAN class="content-warning">
          <%= @post.summary %>
        </SPAN>

        <LABEL for="<%= cwCheckboxID %>"
               class="cwcl noselect"
               tabindex="0">
          <SPAN class="show">
            Show Post
          </SPAN>

          <SPAN class="hide">
            Hide Post
          </SPAN>
        </LABEL>

        <HR />
  <%  end %>

  <DIV>
    <%= if(length(@post.video_attachments) > 0) do %>
      <%= for(video <- @post.video_attachments) do %>
            <VIDEO width="100%"
                   class="video-attachment"
                   title="<%= video.object.name %>"
                   aria-label="<%= video.object.name %>" controls>
              <SOURCE src="<%= Kabare.URLs.URL.to_string(video.object.url) %>"
                      type="<%= video.object.media_type %>">

              Your browser does not support the video tag.
            </VIDEO>
      <%  end %>
    <%  end %>

    <%= if(length(@post.image_attachments) > 0) do %>
          <DIV class="post-images <%= case length(@post.image_attachments) do
                                        1 -> "one";
                                        3 -> "three";
                                        _ -> "general";
                                      end %>">
            <% process_focal = fn(point, invert) ->
                                 50 |> Decimal.mult(if(Decimal.lt?(point, 0)) do
                                                      Decimal.sub(1, Decimal.abs(point));
                                                    else
                                                      Decimal.add(1, point);
                                                    end)
                                    |> Decimal.sub(if invert, do: 100, else: 0)
                                    |> Decimal.abs();
                               end; %>
            <%  prefix = Kabare.Utils.KabareUtils.generate_unique_id(); %>
            <%= for({image, index} <- @post.image_attachments |> Enum.with_index) do %>
                  <A href="#slide-<%= "#{prefix}_#{index + 1}" %>"
                     onclick="document.getElementById('<%= prefix <> "_carousel" %>')
                                      .style
                                      .display = 'inherit'">
                    <IMG src="<%= Kabare.URLs.URL.to_string(image.object.url) %>"
                         alt="<%= image.object.name %>"
                         title="<%= image.object.name %>"
                         <%= if(image.focal_point_x && image.focal_point_y) do %>
                               style="object-position: <%= process_focal.(image.focal_point_x, false) %>%
                                                       <%= process_focal.(image.focal_point_y, true)  %>%"
                         <%  end %> />
                  </A>
            <%  end %>

            <%= render("site_parts/carousel.html",
                       prefix: prefix,
                       images: @post.image_attachments); %>
          </DIV>
    <%  end %>

    <%= if(@post.name) do %>
          <H1>
            <%= @post.name %>
          </H1>
    <%  end %>

    <%= raw(@post.content) %>
  </DIV>
</ARTICLE>

<%= render("site_parts/post-editor.html",
           privacyLevel:  privacyLevel,
           activityPubID: Kabare.URLs.URL.to_string(@post.activity_pub_id)); %>

<FOOTER class="dash_post-interactions">
  <%= render("site_parts/buttons/chat-button.html",
             enableInteraction: true,
             hasBeenSeen:       true,
             inbox:             nil,
             activityPubID:     nil,
             username:          nil,
             creatorActPubID:   nil,
             classToSwitchTo:   "comment-icon_clicked",
             action:            "do") %>

  <!-- reblog button -->
  <%= if(@user && (privacyLevel     !== :targeted            ||
                   creator.actor_id === @user.actor.actor_id)) do %>
    <% postIsReblogged = Enum.member?(Enum.map(@user.actor.shares.object_items,
                                               &(&1.db_id)),
                                      @post.db_id);                               %>
    <%= render("site_parts/buttons/reblog-button.html",
               enableInteraction: true,
               hasBeenSeen:       true,
               inbox:             Kabare.Utils.DatabaseUtils.to_ap_id(creator.inbox),
               activityPubID:     Kabare.URLs.URL.to_string(@post.activity_pub_id),
               username:          creator.preferred_username,
               creatorActPubID:   Kabare.Utils.DatabaseUtils.to_ap_id(creator),
               classToSwitchTo:   unless(postIsReblogged) do
                                    "reblog-icon_clicked"
                                  else
                                    "reblog-icon_unclicked"
                                  end,
               action:            (unless postIsReblogged, do: "do", else: "undo")); %>
  <%  end %>

  <!-- like button -->
  <%= if(@user) do %>
    <% postIsLiked = Enum.member?(Enum.map(@user.actor.liked.object_items,
                                           &(&1.db_id)),
                                  @post.db_id);                              %>
    <%= render("site_parts/buttons/like-button.html",
               enableInteraction: true,
               hasBeenSeen:       true,
               inbox:             Kabare.Utils.DatabaseUtils.to_ap_id(creator.inbox),
               activityPubID:     Kabare.URLs.URL.to_string(@post.activity_pub_id),
               classToSwitchTo:   unless(postIsLiked) do
                                    "like-icon_clicked"
                                  else
                                    "like-icon_unclicked"
                                  end,
               action:            (unless postIsLiked, do: "do", else: "undo")); %>
  <%  end %>

  <!-- delete button -->
  <%= if(@user && @user.user_id === creator.actor_id) do %>
    <%= render("site_parts/buttons/delete-button.html",
               activityPubID:   Kabare.URLs.URL.to_string(@post.activity_pub_id)); %>
  <%  end %>
</FOOTER>
<%  end %>

lib/swanye_web/templates/layout/site_parts/navigation.html.eex
<NAV class="dash_settings_nav">
  <A id="home_icon"
     class="<%= if @page === :dash, do: "highlighted-page-icon", else: "" %>"
     href="/">
    <%= render("site_parts/buttons/home-button.html"); %>

    <DIV style="display: none">
      0
    </DIV>
  </A>

  <%= render("site_parts/buttons/explore-button.html"); %>

  <%= render("site_parts/buttons/ask-button.html"); %>

  <%= render("site_parts/buttons/message-button.html"); %>

  <A id="notifications_icon"
     class="<%= if @page === :notifications, do: "highlighted-page-icon", else: "" %>"
     href="/settings/notifications">
    <%= render("site_parts/buttons/notifications-button.html"); %>

    <% notifs = if @user, do: Enum.reject(@user.notifications, &(&1.has_been_seen)), else: [] %>
    <DIV style="<%= if length(notifs) > 0, do: "", else: "display: none" %>">
      <%= length(notifs) %>
    </DIV>
  </A>

  <A class="<%= if @page === :settings, do: "highlighted-page-icon", else: "" %>"
     href="/settings/account">
    <%= render("site_parts/buttons/profile-button.html"); %>
  </A>
</NAV>

<%= form_for @conn, Routes.search_path(@conn, :search), [method: :get], fn f -> %>
  <%= text_input(f, :terms, placeholder: "Search…") %>
<%  end %>

lib/swanye_web/templates/layout/site_parts/post-editor.html.eex
<FORM action="/frontend/post" class="post-editor"
      method="post"           phx-update="ignore">
  <INPUT name="_csrf_token"
         type="hidden"
         value="<%= Phoenix.Controller.get_csrf_token() %>">

  <INPUT name="title" type="hidden" value="">

  <%= render("site_parts/post_modals/form_editor-bits.html",
             privacyLevel:  @privacyLevel,
             replyActPubID: @activityPubID); %>

  <DIV class="confirm-or-decline">
    <BUTTON type="button"
            class="cancel"
            onclick="this.parentElement.parentElement.classList.remove('show');
                     this.parentElement.parentElement.nextElementSibling.classList.remove('hide');">
			Cancel
		</BUTTON>

    <BUTTON type="button" class="send easyFormSubmit">
      Send
    </BUTTON>
  </DIV>
</FORM>

lib/swanye_web/templates/layout/site_parts/post_template.html.eex
<% creator = Enum.at(@postActivity.actors, 0); %>
<% icons   = Enum.filter(creator.object.images || [], &(&1.is_icon)); %>
<% images  = Enum.filter(creator.object.images || [], &(!&1.is_icon)); %>

<DIV id="<%= @postActivity.object.ap_id %>" class="dash_post-container">
  <A href="<%= Kabare.Utils.ActivityPubUtils.profile_page_path(creator) %>">
    <IMG class="activity-actor-icon"
         src="<%= if(length(icons) > 0) do
                    Kabare.URLs.URL.to_string(Enum.at(icons, 0).object.url);
                  else
                    "/images/missing.png";
                  end %>">
  </A>

  <DIV class="dash_post">
    <%= if(@postActivity.object.object_type === "Announce") do %>
          <ASIDE class="dash_post-reblog-info">
            <A href="<%= Kabare.Utils.ActivityPubUtils.profile_page_path(creator) %>">
              <IMG class="reblog-info-icon"
                   src="<%= if(length(icons) > 0) do
                              Kabare.URLs.URL.to_string(Enum.at(icons, 0).object.url);
                            else
                              "/images/missing.png";
                            end %>">
            </A>

            <DIV class="reblog-info">
              <A class="reblog-info-poster ellipsize"
                 href="<%= Kabare.Utils.ActivityPubUtils.profile_page_path(creator) %>">
                <B class="ellipsize">
                  <%= if(creator.object.name) do %>
                        <%= creator.object.name %>
                  <%  else %>
                        <%= creator.preferred_username %>
                  <%  end %>
                </B>
              </A>

              <% originator = List.first(@postActivity.acted_upon_object
                                                      .actor_attributees); %>
              <DIV class="reblog-info-reblogged-from ellipsize">
                <%= render("site_parts/buttons/reblog-button.html",
                           enableInteraction: false,
                           hasBeenSeen:       true,
                           inbox:             nil,
                           activityPubID:     nil,
                           username:          nil,
                           creatorActPubID:   nil,
                           classToSwitchTo:   "reblog-icon_clicked",
                           action:            nil); %>

                <A href="<%= Kabare.Utils.ActivityPubUtils.profile_page_path(originator) %>">
                  <%= originator.preferred_username %>
                </A>
              </DIV>
            </DIV>
          </ASIDE>
    <%  end %>

    <%= render("site_parts/inner-post_template.html", user: @user,
               post: @postActivity.acted_upon_object, init: @postActivity.acted_upon_object); %>
  </DIV>
</DIV>

lib/swanye_web/templates/layout/site_parts/side_buttons.html.eex
<DIV class="dash_side">
  <A class="dash_button" href="#new-post-editor">
    <P>
      Aa
    </P>

    <DIV>
      Text
    </DIV>
  </A>

  <A class="dash_button" href="#new-image-post-editor">
    <SVG viewBox="0 0 30 30" xmlns="http://www.w3.org/2000/svg">
      <PATH fill="#fff" d="M7 5H6a1 1 0 0 0-1 1h3a1 1 0 0 0-1-1z" />

      <CIRCLE fill="#fff" cx="15" cy="15" r="5" />

      <PATH fill="#fff" d="M26 7h-4.264a2 2 0 0 1-1.789-1.106l-.394-.789A2.002 2.002 0 0 0 17.764 4h-5.528a2 2 0 0 0-1.789 1.106l-.394.789A2.002 2.002 0 0 1 8.264 7H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2h22a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2zM15 22c-3.86 0-7-3.14-7-7s3.14-7 7-7 7 3.14 7 7-3.14 7-7 7zm9-11a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
    </SVG>

    <DIV>
      Photo
    </DIV>
  </A>

  <DIV class="dash_button">
    <SVG xmlns="http://www.w3.org/2000/svg" height="1792"
         viewBox="0 0 1792 1792"            width="1792">
      <PATH fill="#FFFFFF"
            d="M832 320v704q0 104-40.5 198.5t-109.5 163.5-163.5 109.5-198.5 40.5h-64q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h64q106 0 181-75t75-181v-32q0-40-28-68t-68-28h-224q-80 0-136-56t-56-136v-384q0-80 56-136t136-56h384q80 0 136 56t56 136zm896 0v704q0 104-40.5 198.5t-109.5 163.5-163.5 109.5-198.5 40.5h-64q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h64q106 0 181-75t75-181v-32q0-40-28-68t-68-28h-224q-80 0-136-56t-56-136v-384q0-80 56-136t136-56h384q80 0 136 56t56 136z" />
    </SVG>

    <DIV>
      Quote
    </DIV>
  </DIV>

  <DIV class="dash_button">
    <SVG xmlns="http://www.w3.org/2000/svg" width="80"
         viewBox="0 0 80 80"                height="80">
      <PATH fill="#FFFFFF"
            d="M29.298 63.471l-4.048 4.02c-3.509 3.478-9.216 3.481-12.723 0-1.686-1.673-2.612-3.895-2.612-6.257s.927-4.585 2.611-6.258l14.9-14.783c3.088-3.062 8.897-7.571 13.131-3.372a4.956 4.956 0 1 0 6.985-7.034c-7.197-7.142-17.834-5.822-27.098 3.37L5.543 47.941C1.968 51.49 0 56.21 0 61.234s1.968 9.743 5.544 13.292C9.223 78.176 14.054 80 18.887 80c4.834 0 9.667-1.824 13.348-5.476l4.051-4.021a4.955 4.955 0 0 0 .023-7.009 4.96 4.96 0 0 0-7.011-.023zM74.454 6.044c-7.73-7.67-18.538-8.086-25.694-.986l-5.046 5.009a4.958 4.958 0 0 0 6.986 7.034l5.044-5.006c3.707-3.681 8.561-2.155 11.727.986a8.752 8.752 0 0 1 2.615 6.258 8.763 8.763 0 0 1-2.613 6.259l-15.897 15.77c-7.269 7.212-10.679 3.827-12.134 2.383a4.957 4.957 0 0 0-6.985 7.034c3.337 3.312 7.146 4.954 11.139 4.954 4.889 0 10.053-2.462 14.963-7.337l15.897-15.77C78.03 29.083 80 24.362 80 19.338c0-5.022-1.97-9.743-5.546-13.294z" />
    </SVG>

    <DIV>
      Link
    </DIV>
  </DIV>

  <DIV class="dash_button">
    <SVG xmlns="http://www.w3.org/2000/svg" width="500"
         viewBox="0 0 500 500"              height="500">
      <PATH clip-rule="evenodd" fill="#FFFFFF"
            fill-rule="evenodd" d="M36.992 326.039c0 20.079 16.262 36.34 36.34 36.34h54.513v56.062c0 10.087 8.181 18.168 18.172 18.168 5.092 0 9.714-2.095 12.989-5.448l68.78-68.781h199.881c20.078 0 36.34-16.261 36.34-36.34V98.902c0-20.079-16.262-36.341-36.34-36.341H73.333c-20.079 0-36.34 16.262-36.34 36.341v227.137zm109.026-104.482c0-12.536 10.177-22.713 22.713-22.713 12.536 0 22.713 10.177 22.713 22.713 0 12.537-10.177 22.713-22.713 22.713-12.537 0-22.713-10.177-22.713-22.713zm81.769 0c0-12.536 10.177-22.713 22.713-22.713 12.537 0 22.715 10.177 22.715 22.713 0 12.537-10.178 22.713-22.715 22.713-12.536 0-22.713-10.177-22.713-22.713zm81.769 0c0-12.536 10.176-22.713 22.715-22.713 12.537 0 22.711 10.177 22.711 22.713 0 12.537-10.174 22.713-22.711 22.713-12.54 0-22.715-10.177-22.715-22.713z" />
    </SVG>

    <DIV>
      Chat
    </DIV>
  </DIV>

  <DIV class="dash_button">
    <SVG xmlns="http://www.w3.org/2000/svg" width="96"
         viewBox="0 0 96 96"                height="96">
      <PATH fill="none"
            d="M-1-1h582v402H-1z" />

      <G>
        <PATH fill="#FFFFFF"
              d="M71.8 43.5L30.6 21.8c-1.9-1-4.2-.9-6 .2-1.6 1-2.6 2.7-2.6 4.5v41.3c0 1.8 1 3.5 2.6 4.5 1 .6 2.1.9 3.2.9 1 0 2-.2 2.8-.7l41.2-21.7c1.3-.7 2.2-2.1 2.2-3.6 0-1.6-.8-3-2.2-3.7z" />
      </G>
    </SVG>

    <DIV>
      Audio
    </DIV>
  </DIV>

  <DIV class="dash_button">
    <SVG xmlns="http://www.w3.org/2000/svg" width="24"
         viewBox="0 0 24 24"                height="24">
      <PATH fill="none" d="M-1-1h582v402H-1z" />

      <G>
        <PATH fill="#FFFFFF"
              d="M22.525 7.149C22.365 7.05 22.183 7 22 7c-.153 0-.306.035-.447.105L19 8.382V8c0-1.654-1.346-3-3-3H5C3.346 5 2 6.346 2 8v8c0 1.654 1.346 3 3 3h11c1.654 0 3-1.346 3-3v-.382l2.553 1.276c.141.071.294.106.447.106.183 0 .365-.05.525-.149.295-.183.475-.504.475-.851V8c0-.347-.18-.668-.475-.851zM7 13.5c-.829 0-1.5-.671-1.5-1.5s.671-1.5 1.5-1.5 1.5.671 1.5 1.5-.671 1.5-1.5 1.5z" />
      </G>
    </SVG>

    <DIV>
      Video
    </DIV>
  </DIV>
</DIV>

lib/swanye_web/templates/layout/site_parts/warning-modal.html.eex
<SECTION id="warning-modal" >
  <DIV>
    <DIV class="warning-text">
      <H3>
        Are you sure you want to delete this post?
      </H3>
    </DIV>

    <DIV class="warning-buttons">
      <BUTTON class="cancel">
        Cancel
      </BUTTON>

      <BUTTON class="affirm">
        O. K.
      </BUTTON>
    </DIV>
  </DIV>
</SECTION>